### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [Gruruya/nmostr#1]
Hi,

I want to help, but I want to know if this project is active. Is this project active?

**Comment by Gruruya** [comment]
Yeah I'm here. I'm using it for an in-development project and will take whatever improvements you come up with.

**Comment by ghost** [comment]
Hi @Gruruya, how are you?

> Yeah I'm here. I'm using it for an in-development project and will take whatever improvements you come up with.

thanks for all information here!

**Comment by Gruruya** [comment]
I'm good, thanks. Good luck with Nim, it's a great language.
